#nullable enable

using FluentAssertions;
using SystemdServiceMonitor.Enums;
using SystemdServiceMonitor.Models;
using Xunit;

/// <summary>
/// Tests for the ServiceStatus class.
/// </summary>
namespace SystemdServiceMonitor.Tests;

public class ServiceStatusTests
{
    /// <summary>
    /// Tests that ServiceStatus can be instantiated with default values.
    /// </summary>
    [Fact]
    public void ServiceStatus_DefaultConstructor_InitializesCorrectly()
    {
        // Arrange & Act
        var status = new ServiceStatus();

        // Assert
        status.Id.Should().NotBe(Guid.Empty);
        status.UnitName.Should().BeEmpty();
        status.State.Should().Be(ServiceState.Unknown);
        status.SubState.Should().Be(ServiceSubState.Unknown);
        status.IsEnabled.Should().BeFalse();
        status.IsRunning.Should().BeFalse();
        status.ProcessId.Should().Be(0);
        status.CpuUsagePercent.Should().Be(0);
        status.MemoryUsageMb.Should().Be(0);
        status.HasFailed.Should().BeFalse();
        status.FailureReason.Should().BeEmpty();
        status.ExitCode.Should().Be(0);
        status.UptimeSeconds.Should().Be(0);
        status.HealthStatus.Should().Be(HealthStatus.Unknown);
        status.HealthMessage.Should().BeEmpty();
        status.RecordedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
    }

    /// <summary>
    /// Tests that ServiceStatus can be instantiated with custom values.
    /// </summary>
    [Fact]
    public void ServiceStatus_CustomValues_InitializesCorrectly()
    {
        // Arrange
        var customId = Guid.NewGuid();
        var customTime = DateTime.UtcNow.AddMinutes(-5);

        // Act
        var status = new ServiceStatus
        {
            Id = customId,
            UnitName = "nginx.service",
            State = ServiceState.Active,
            SubState = ServiceSubState.Running,
            IsEnabled = true,
            IsRunning = true,
            ProcessId = 12345,
            CpuUsagePercent = 45.5m,
            MemoryUsageMb = 256,
            HasFailed = false,
            FailureReason = "None",
            ExitCode = 0,
            UptimeSeconds = 3600,
            HealthStatus = HealthStatus.Healthy,
            HealthMessage = "Service is running normally",
            RecordedAt = customTime
        };

        // Assert
        status.Id.Should().Be(customId);
        status.UnitName.Should().Be("nginx.service");
        status.State.Should().Be(ServiceState.Active);
        status.SubState.Should().Be(ServiceSubState.Running);
        status.IsEnabled.Should().BeTrue();
        status.IsRunning.Should().BeTrue();
        status.ProcessId.Should().Be(12345);
        status.CpuUsagePercent.Should().Be(45.5m);
        status.MemoryUsageMb.Should().Be(256);
        status.HasFailed.Should().BeFalse();
        status.FailureReason.Should().Be("None");
        status.ExitCode.Should().Be(0);
        status.UptimeSeconds.Should().Be(3600);
        status.HealthStatus.Should().Be(HealthStatus.Healthy);
        status.HealthMessage.Should().Be("Service is running normally");
        status.RecordedAt.Should().Be(customTime);
    }

    /// <summary>
    /// Tests that ServiceStatus Id is auto-generated when not set.
    /// </summary>
    [Fact]
    public void ServiceStatus_Id_AutoGeneratedWhenNotSet()
    {
        // Arrange & Act
        var status1 = new ServiceStatus();
        var status2 = new ServiceStatus();

        // Assert
        status1.Id.Should().NotBe(Guid.Empty);
        status2.Id.Should().NotBe(Guid.Empty);
        status1.Id.Should().NotBe(status2.Id); // Should be unique
    }

    /// <summary>
    /// Tests that ServiceStatus RecordedAt is set to current time by default.
    /// </summary>
    [Fact]
    public void ServiceStatus_RecordedAt_DefaultValueIsCurrentTime()
    {
        // Arrange & Act
        var status = new ServiceStatus();

        // Assert
        status.RecordedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
    }

    /// <summary>
    /// Tests that ServiceStatus can be modified after creation.
    /// </summary>
    [Fact]
    public void ServiceStatus_Properties_CanBeModified()
    {
        // Arrange
        var status = new ServiceStatus();

        // Act
        status.UnitName = "test.service";
        status.State = ServiceState.Active;
        status.IsEnabled = true;
        status.CpuUsagePercent = 75.3m;
        status.HasFailed = true;
        status.FailureReason = "Test failure";
        status.RecordedAt = DateTime.UtcNow.AddHours(-1);

        // Assert
        status.UnitName.Should().Be("test.service");
        status.State.Should().Be(ServiceState.Active);
        status.IsEnabled.Should().BeTrue();
        status.CpuUsagePercent.Should().Be(75.3m);
        status.HasFailed.Should().BeTrue();
        status.FailureReason.Should().Be("Test failure");
        status.RecordedAt.Should().BeCloseTo(DateTime.UtcNow.AddHours(-1), TimeSpan.FromSeconds(1));
    }
}
