version: '3.4'
services:
  systemd-service-monitor:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ALERT_ENABLED=true
    restart: unless-stopped